spring:
  application:
    name: "PPosiraegi-Backend"
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 Problem


app:
  jwt:
    expiration-ms: 1h